FROM openbox-android

# NOTE: setup emulator
# ANDROID SDK root
# pre-request
RUN apt install -y git  unzip wget \
  openjdk-11-jdk openjdk-17-jdk \
  qemu-system-x86

RUN mkdir -p /root/Android
# RUN wget -O tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
RUN cd /root/Android && \
  wget -O tools.zip http://192.168.10.61:8181/commandlinetools-linux-8512546_latest.zip && \
  unzip tools.zip && \
  rm tools.zip

ENV ANDROID_HOME $HOME/Android
ENV ANDROID_SDK_ROOT $HOME/Android
ENV ANDROID_USER_HOME $HOME/.android

ENV PATH $PATH:$ANDROID_HOME/tools
ENV PATH $PATH:$ANDROID_HOME/tools/bin
ENV PATH $PATH:$ANDROID_HOME/platform-tools
ENV PATH $PATH:$ANDROID_HOME/cmdline-tools/bin

RUN yes | sdkmanager --verbose --sdk_root=$ANDROID_HOME --licenses
RUN echo y | sdkmanager --verbose --sdk_root=$ANDROID_HOME "platform-tools" "emulator"
RUN echo y | sdkmanager --verbose --sdk_root=$ANDROID_HOME "system-images;android-25;default;x86"

# manaually create this directory but i don't know why, documetated
RUN mkdir -p $ANDROID_HOME/platforms

# create AVD
RUN echo no | avdmanager -v create avd -f -n test_nexus -k 'system-images;android-25;default;x86' 

RUN echo y | sdkmanager --verbose --sdk_root=$ANDROID_HOME "tools"

# emulator setup ends here
