FROM ubuntu:22.04

RUN sed -i 's/\/\/archive\.ubuntu\.com/\/\/hk\.archive\.ubuntu\.com/g' /etc/apt/sources.list && \
  sed -i 's/\/\/security\.ubuntu\.com/\/\/hk\.archive\.ubuntu\.com/g' /etc/apt/sources.list

EXPOSE 5900 

ENV HOME /root
ENV TZ Etc/UTC
ENV SHELL /bin/bash
ENV PS1='# '
ENV DEBIAN_FRONTEND=noninteractive
ENV PASSWORD="root"

RUN apt update 
RUN apt install -y \
  supervisor \
  openbox tint2 tigervnc-standalone-server \
  pcmanfm xfce4-terminal procps curl telnet iproute2

RUN mkdir /root/.vnc
RUN echo 123456 | vncpasswd -f > /root/.vnc/passwd
RUN chmod 600 /root/.vnc/passwd

ADD etc/xdg/pcmanfm /root/.config/pcmanfm
ADD etc /etc

# # original openbox docker ends here

# launch line
# CMD ["/usr/bin/supervisord","-c","/etc/supervisord-screen.conf"]
